### ISSUE TITLE
我执行app.py提示模块找不到

### ISSUE THREAD

**Issue by wangxingsheng** [yuanzhoulvpi2017/WechatGroupRobot#1]
Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\WechatGroupRobot-main\app.py", line 3, in <module>
    from transtext import *
  File "C:\Users\DELL\Desktop\WechatGroupRobot-main\transtext.py", line 4, in <module>
    from revChatGPT.revChatGPT import Chatbot
ModuleNotFoundError: No module named 'revChatGPT.revChatGPT'
PS C:\Users\DELL\Desktop\WechatGroupRobot-main>
请问这是什么情况

**Comment by warlock-lv** [comment]
> 
怎么样，你解决问题了吗？  wx   457880341

**Comment by mcc1095319343** [comment]
+1
